In [1]:
#########################################################################
###   Alzheimer
###   RGSJr
###   Janeiro/2026
#########################################################################

In [17]:
import pandas as pd

In [18]:
print(pd.__version__)

2.3.0+4.g1dfc98e16a

In [19]:
## Ler ADNI TADPOLE_D3
#df_temp2 = pd.read_csv("TADPOLE_D3.csv",low_memory=False)
#df_temp2.head()

In [20]:
# Ler ADNI TADPOLE_D1_D2
df_temp = pd.read_csv("TADPOLE_D1_D2.csv",low_memory=False)
df_temp.head()

,RID,PTID,VISCODE,SITE,D1,D2,COLPROT,ORIGPROT,EXAMDATE,DX_bl,...,PHASE_UPENNBIOMK9_04_19_17,BATCH_UPENNBIOMK9_04_19_17,KIT_UPENNBIOMK9_04_19_17,STDS_UPENNBIOMK9_04_19_17,RUNDATE_UPENNBIOMK9_04_19_17,ABETA_UPENNBIOMK9_04_19_17,TAU_UPENNBIOMK9_04_19_17,PTAU_UPENNBIOMK9_04_19_17,COMMENT_UPENNBIOMK9_04_19_17,update_stamp_UPENNBIOMK9_04_19_17
0,2,011_S_0002,bl,11,1,1,ADNI1,ADNI1,2005-09-08,CN,...,,,,,,,,,,
1,3,011_S_0003,bl,11,1,0,ADNI1,ADNI1,2005-09-12,AD,...,ADNI1,UPENNBIOMK9,P06-MP02-MP01,P06-MP02-MP01/2,2016-12-14,741.5,239.7,22.83,NaN,2017-04-20 14:39:54.0
2,3,011_S_0003,m06,11,1,0,ADNI1,ADNI1,2006-03-13,AD,...,,,,,,,,,,
3,3,011_S_0003,m12,11,1,0,ADNI1,ADNI1,2006-09-12,AD,...,ADNI1,UPENNBIOMK9,P06-MP02-MP01,P06-MP02-MP01/2,2016-12-14,601.4,251.7,24.18,NaN,2017-04-20 14:39:54.0
4,3,011_S_0003,m24,11,1,0,ADNI1,ADNI1,2007-09-12,AD,...,,,,,,,,,,

In [21]:
#df_temp.columns.tolist()

In [22]:
df_temp.shape

(12741, 1907)

In [23]:
# Selecionar as colunas de interesse
df_trab = df_temp[['RID','EXAMDATE','Ventricles','Hippocampus','WholeBrain',
                   'Entorhinal','Fusiform','MidTemp','ICV','CDRSB','MMSE','RAVLT_learning',
                   'RAVLT_immediate','RAVLT_forgetting','RAVLT_perc_forgetting_bl',
                   'ADAS11','ADAS13','FAQ','FDG','AV45','APOE4','AGE','PTEDUCAT','DX']]

In [24]:
# Eliminar os registros com ausencia de dados (NAN)
dataset = df_trab.dropna(axis=0)

In [25]:
dataset.shape

(1080, 24)

In [26]:
# Reiniciar o ídice
dataset = dataset.reset_index(drop=True)

In [27]:
# Deixar apenas uma instância por parciente - pegar a última consulta do paciente no banco de dados
vc = dataset['RID'].value_counts()
df_final = pd.DataFrame(columns=dataset.columns)
for i in range(len(vc)):
    df_paciente = dataset[dataset['RID'] == vc.index[i]]
    df_linha = df_paciente[df_paciente['EXAMDATE'] == dataset[dataset['RID'] == vc.index[i]]['EXAMDATE'].max()]
    df_final = pd.concat([df_final, df_linha],ignore_index=True)

C:\Users\j_df\AppData\Local\Temp\ipykernel_31820\4150555454.py:7: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_final = pd.concat([df_final, df_linha],ignore_index=True)

In [28]:
dataset = df_final

In [29]:
dataset.shape

(842, 24)

In [30]:
df_final["DX"].value_counts()

DX
MCI                388
NL                 291
Dementia           126
MCI to Dementia     22
NL to MCI            8
MCI to NL            5
Dementia to MCI      2
Name: count, dtype: int64

In [15]:
# Eliminar DEMENTIA => MCI
df_remove = dataset.loc[dataset['DX'] == 'Dementia to MCI']
dataset = dataset.drop(df_remove.index)

In [16]:
# Eliminar MCI => NL
df_remove = dataset.loc[dataset['DX'] == 'MCI to NL']
dataset = dataset.drop(df_remove.index)

In [38]:
df_final = dataset

In [39]:
# Agrupar e numerar as classes
# CN  = 0  (NL)
# MCI = 1  (MCI)
# AD  = 2  (Dementia)
for i in range(0,len(df_final)):
    if df_final.iloc[i,-1] == 'NL':
        df_final.iloc[i,-1] = 0
    if df_final.iloc[i,-1] == 'MCI':
        df_final.iloc[i,-1] = 1
    if df_final.iloc[i,-1] == 'NL to MCI':
        df_final.iloc[i,-1] = 1
    if df_final.iloc[i,-1] == 'Dementia':
        df_final.iloc[i,-1] = 2    
    if df_final.iloc[i,-1] == 'MCI to Dementia':
        df_final.iloc[i,-1] = 2

In [40]:
# Remover o ID do paciente e a data do exame
df_final = df_final.drop(['RID','EXAMDATE'], axis=1)

In [41]:
#Salvar em CSV
df_final.to_csv('ADNI_3C_2026.csv',index = False)

In [42]:
df_final

,Ventricles,Hippocampus,WholeBrain,Entorhinal,Fusiform,MidTemp,ICV,CDRSB,MMSE,RAVLT_learning,...,RAVLT_perc_forgetting_bl,ADAS11,ADAS13,FAQ,FDG,AV45,APOE4,AGE,PTEDUCAT,DX
0,16745.0,7889.0,1053970.0,3461.0,19774.0,20866.0,1451710.0,0.5,30.0,5.0,...,38.46150,1.0,3.0,0.0,1.39368,1.147700,1.0,55.5,19,1
1,30336.0,7672.0,1026760.0,3925.0,19019.0,19666.0,1528010.0,0.0,28.0,6.0,...,63.63640,5.0,9.0,0.0,1.47245,1.128200,0.0,71.7,14,0
2,22592.0,6519.0,991938.0,3445.0,18749.0,23103.0,1390820.0,0.5,27.0,7.0,...,35.71430,5.0,10.0,1.0,1.40276,1.200010,1.0,64.1,16,1
3,44654.0,6703.0,944838.0,3800.0,17649.0,19770.0,1475570.0,0.0,30.0,6.0,...,33.33330,4.0,7.0,0.0,1.27286,0.878026,0.0,84.1,19,0
4,34586.0,7268.0,977055.0,3665.0,19939.0,18606.0,1470240.0,0.0,28.0,6.0,...,0.00000,9.0,10.0,0.0,1.42419,0.918353,0.0,72.6,20,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
837,19925.0,7868.0,1122500.0,3905.0,19216.0,25453.0,1469080.0,0.0,30.0,6.0,...,13.33330,4.0,5.0,0.0,1.36528,1.064850,1.0,67.5,20,0
838,32881.0,5865.0,997942.0,2929.0,14891.0,18189.0,1477110.0,3.5,25.0,3.0,...,100.00000,17.0,28.0,9.0,1.12816,1.626540,1.0,72.9,12,1
839,27104.0,5665.0,996229.0,3722.0,13472.0,21272.0,1242190.0,1.0,27.0,4.0,...,44.44440,11.0,16.0,1.0,1.24432,1.171170,2.0,74.3,14,1
840,25729.0,7675.0,926426.0,2972.0,16387.0,20005.0,1267590.0,1.5,29.0,2.0,...,100.00000,9.0,15.0,3.0,1.28645,1.505620,0.0,82.5,12,1
841,10954.0,6098.0,1015560.0,3324.0,19063.0,19328.0,1459670.0,0.5,30.0,7.0,...,-9.09091,7.0,10.0,0.0,1.29485,1.048590,0.0,80.4,12,1

In [45]:
df_final["DX"].value_counts()

DX
1    396
0    291
2    148
Name: count, dtype: int64